name: Changelog verification

on:
  pull_request:
    branches: [ main ]

jobs:
  changelog-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for changelog entry
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
        run: |
          (
            git fetch origin ${{ github.base_ref }} --depth 1 && \
            git diff remotes/origin/${{ github.base_ref }} --name-only | grep -P "\.changes/[0-9a-f-]+\.json"
          )
          CHANGELOG_EXISTS=$?          
          if [ $CHANGELOG_EXISTS -ne 0 ]; then
            echo "::error ::No new/updated changelog entry found in /.changes directory. Please either:"
            echo "::error ::* Add a changelog entry (in most cases) –or–"
            echo "::error ::* Add the 'no-changelog' label to this PR (in rare cases not warranting a changelog entry)"
          fi          
          exit $CHANGELOG_EXISTS
