name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - 'feat-*'
  workflow_dispatch:

env:
  BUILDER_VERSION: v0.8.22
  BUILDER_SOURCE: releases
  # host owned by CRT team to host aws-crt-builder releases. Contact their on-call with any issues
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: smithy-kotlin
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  linux-compat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build and Test ${{ env.PACKAGE_NAME }}
      run: ./gradlew :runtime:protocol:http-client-engines:http-client-engine-okhttp:jvmTest --tests aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBodyTest.testJobCancelled

  macos-compat:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build and Test ${{ env.PACKAGE_NAME }}
      run: ./gradlew :runtime:protocol:http-client-engines:http-client-engine-okhttp:jvmTest --tests aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBodyTest.testJobCancelled

  windows-compat:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build and Test ${{ env.PACKAGE_NAME }}
        run: ./gradlew :runtime:protocol:http-client-engines:http-client-engine-okhttp:jvmTest --tests aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBodyTest.testJobCancelled

  downstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build and Test ${{ env.PACKAGE_NAME }} Downstream Consumers
      run: |
        python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder')"
        chmod a+x builder
        echo "kotlinWarningsAsErrors=true" >> $GITHUB_WORKSPACE/local.properties
        ./builder build -p ${{ env.PACKAGE_NAME }} --spec downstream
