name: Build Downstream Dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILDER_VERSION: fix-dependency-steps
  BUILDER_SOURCE: channels
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: smithy-kotlin
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  downstream:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build and Test ${{ env.PACKAGE_NAME }} Downstream Consumers
      env:
        CI_USER: ${{ secrets.CI_USER}}
        CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
      run: |
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
        cat $GITHUB_EVENT_PATH
        # python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder')"
        # chmod a+x builder
        # GIT_ASKPASS="$(pwd)/scripts/git-ci-askpass.sh" ./builder build -p ${{ env.PACKAGE_NAME }} --spec downstream
