name: Lint

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - 'main'

env:
  PACKAGE_NAME: smithy-kotlin

jobs:
  linux-compat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Lint ${{ env.PACKAGE_NAME }}
    - name: ktlint
      run: |
        ./gradlew ktlint
