name: Snyk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 17:00 UTC (9am/10am Pacific) every Tuesday
    - cron:  '0 17 * * 2'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and configure Snyk CLI
        run: |
          curl -Lo ./snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod 755 snyk
      - name: Execute scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: ./snyk test --severity-threshold=medium --all-projects --policy-path=.
